### ISSUE TITLE
Error objects cannot be expanded + Fix for #20

### ISSUE THREAD

**Issue by skleeschulte** [alexkuz/react-json-tree#22]
Error objects in the state tree cannot be expanded. Thats because iterating with for...in and hasOwnProperty doesn't work here. However this should easily be fixed by adding this before [line 30 in JSONObjectNode.js](https://github.com/chibicode/react-json-tree/blob/master/src/JSONObjectNode.js#L30):

    if (data instanceof Error) {
        data = Object.getOwnPropertyNames(data).reduce(function (errorObj, prop) {
            errorObj[prop] = data[prop];
            return errorObj;
        }, {});
    }

In addition, to solve [Objects without prototype chain are broken #20 ](https://github.com/chibicode/react-json-tree/issues/20), [line 32 in JSONObjectNode.js](https://github.com/chibicode/react-json-tree/blob/master/src/JSONObjectNode.js#L32) could be changed to:

    if (Object.getPrototypeOf(data) === null || data.hasOwnProperty(key)) {

(IMHO thats better than PR [Fixes #20, expanding of objects without prototype #21](https://github.com/chibicode/react-json-tree/pull/21).)

I would create a pull request, but I cannot test this, because I cannot build the package. (I cloned it from github, but get lot's of errors on `npm install`, `npm build` and `npm run lint`. Even after fixing `npm install` and `npm build` (by removing all the carets from the dependency versions in package.json and installing babel@5.6), with `npm build` the output in `lib` looks different from what I get from `npm install react-json-tree`.)

But I'm sure someone can do it. :)

**Comment by chibicode** [comment]
Thanks! Closed by #23

**Comment by skleeschulte** [comment]
PR [#23](https://github.com/chibicode/react-json-tree/pull/23) only fixes issue [#20](https://github.com/chibicode/react-json-tree/issues/20) by adding `if (Object.getPrototypeOf(data) === null || data.hasOwnProperty(key)) {`. The main thing this issue is about is that errors cannot be extended, which is because the [for...in loop](https://github.com/chibicode/react-json-tree/blob/master/src/JSONObjectNode.js#L31) doesn't iterate over Error instance properties.

**Comment by chibicode** [comment]
@skleeschulte sorry I read it wrong, reopened this issue

**Comment by alexkuz** [comment]
Should be fixed by https://github.com/alexkuz/react-json-tree/commit/dadf3d3a07db749abb3d1ece3ec51627eb650165

**Comment by dorian-marchal** [comment]
Looks like the issue is still there (in `redux-devtools`, at least, which use v0.11).
