### ISSUE TITLE
How do you set the root to be closed by default?

### ISSUE THREAD

**Issue by jbgarr** [alexkuz/react-json-tree#49]
Can you please explain how to use the 'shouldExpandNode' prop? An example would be useful in this case. Thanks!

**Comment by alexkuz** [comment]
Take a look at default behaviour:
```
shouldExpandNode: (keyName, data, level) => level === 0, // expands root by default
```
it expands root (zero-level) node.
Just check node key name, it's value or it's nesting level and return `true` if you need it to be expanded by default.

**Comment by jbgarr** [comment]
Thanks for the reply. I did see that and tried to return false if the level was 0 like the following:
`<JSONTree data={category} shouldExpandNode={(keyName, data, level) => {if(level === 0){return false;}}}/>`

That didn't see to work though, so I'm not sure what the proper usage is. How would I go about collapsing `root` in this case?

**Comment by alexkuz** [comment]
@jbgarr hmm, this seems like a bug, if you return false value it should be collapsed. I'll check it out.

**Comment by jbgarr** [comment]
@alexkuz Ok, great, thanks. I thought I was doing the right thing, but wasn't sure.

**Comment by alexkuz** [comment]
@jbgarr I've published `v0.8.0` - there was a problem with deprecated props `expandRoot` and `expandAll`, so I removed them. Thanks for this!

**Comment by jbgarr** [comment]
@alexkuz Awesome! Just grabbed the new version and it looks good. Thanks for the quick response! It's a great tool.

**Comment by astanciu** [comment]
FYI, console still throws:
`Required prop expanded was not specified in JSONArrow. Check the render method of JSONNestedNode.`

v0.10.0
